using FluentAssertions;
using TypedGML.Compiler.Tests.Helpers;

namespace TypedGML.Compiler.Tests.Emission;

public sealed class StaticEmissionTests
{
    [Fact]
    public void Test_StaticMethod_EmittedInStaticCtor()
    {
        var gml = Compile("public class MathHost { public static number Abs(number x) { return x; } }").GetFile("MathHost.gml")!;
        GmlAssert.ContainsPattern(gml, "global.MathHost_Abs = function(x) {");
        GmlAssert.HasPragma(gml, "MathHost_static_ctor");
    }

    [Fact]
    public void Test_StaticField_EmittedInStaticCtor() =>
        GmlAssert.ContainsPattern(Compile("public class Config { public static number X = 5; }").GetFile("Config.gml")!, "global.Config_X = 5;");

    [Fact]
    public void Test_StaticProperty_EmittedInStaticCtor()
    {
        var gml = Compile("public class Config { public static number Volume { get; set; } }").GetFile("Config.gml")!;
        GmlAssert.ContainsPattern(gml, "global.Config_get_Volume = function() {");
        GmlAssert.ContainsPattern(gml, "global.Config_set_Volume = function(value) {");
    }

    [Fact]
    public void Test_StaticCallSite() =>
        GmlAssert.ContainsPattern(Compile("public class MathHost { public static number Abs(number x) { return x; } public number Run() { return MathHost.Abs(1); } }").GetFile("MathHost.gml")!, "return global.MathHost_Abs(1);");

    [Fact]
    public void Test_ConstNotGlobal()
    {
        var gml = Compile("public class Config { public const number C = 1; }").GetFile("Config.gml")!;
        GmlAssert.HasMacro(gml, "Config_C", "1");
        GmlAssert.NotContainsPattern(gml, "global.Config_C");
        GmlAssert.NotContainsPattern(gml, "Config_static_ctor");
    }

    [Fact]
    public void Test_StaticCtorExplicitBody_AfterAutoGenerated()
    {
        var gml = Compile("public class Config { public static number X = 5; static constructor() { X = 7; } }").GetFile("Config.gml")!;
        gml.IndexOf("global.Config_X = 5;", StringComparison.Ordinal).Should().BeGreaterThan(-1);
        gml.IndexOf("global.Config_X = 7;", StringComparison.Ordinal).Should().BeGreaterThan(gml.IndexOf("global.Config_X = 5;", StringComparison.Ordinal));
    }

    [Fact]
    public void Test_StaticConstructorKeyword_EmitsStaticCtorFunction()
    {
        var gml = Compile("public class Foo { static constructor() { } }").GetFile("Foo.gml")!;
        GmlAssert.ContainsPattern(gml, "function Foo_static_ctor()");
    }

    private static CompileResult Compile(string source) => CompilerFixture.Compile(source);
}
